// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ImportadoraApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112005106_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImportadoraApi.Models.Almacen", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("text");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombreencargado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Almacenes");
                });

            modelBuilder.Entity("ImportadoraApi.Models.CierreDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlmacenId")
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadVentas")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GananciaNeta")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalGastos")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalIngresos")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CierresDiarios");
                });

            modelBuilder.Entity("ImportadoraApi.Models.CierreDiarioRegistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CierreDiarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegistroFinancieroId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CierreDiarioId");

                    b.HasIndex("RegistroFinancieroId");

                    b.ToTable("CierreDiarioRegistros");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Consignacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MontoPendiente")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VentaId")
                        .IsUnique();

                    b.ToTable("Consignaciones");
                });

            modelBuilder.Entity("ImportadoraApi.Models.ConsignacionMovimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsignacionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConsignacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ConsignacionMovimientos");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Contenedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaArribo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreContenedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PorcentajeVendido")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Contenedores");
                });

            modelBuilder.Entity("ImportadoraApi.Models.ContenedorDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantidadRecibida")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Cantidadactual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Cantidadmerma")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Cantproductosxpacka")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ContenedorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("numeric");

                    b.Property<bool>("Packa")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContenedorId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ContenedorDetalles");
                });

            modelBuilder.Entity("ImportadoraApi.Models.CostosContenedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Idcotenedor")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Idcotenedor");

                    b.ToTable("CostosContenedores");
                });

            modelBuilder.Entity("ImportadoraApi.Models.DistribucionProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ContenedorDetalleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrigenId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenId");

                    b.HasIndex("ContenedorDetalleId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DistribucionProductos");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Inventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenId")
                        .IsUnique();

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("ImportadoraApi.Models.InventarioProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantproductosxpacka")
                        .HasColumnType("numeric");

                    b.Property<Guid>("InventarioId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Packa")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("InventarioId");

                    b.HasIndex("ProductoId");

                    b.ToTable("InventarioProductos");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Merma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mermas");
                });

            modelBuilder.Entity("ImportadoraApi.Models.MovimientoInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InventarioProductoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("OrSigen")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("StockAnterior")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StockPosterior")
                        .HasColumnType("numeric");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventarioProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Pagos", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VentaDetalleId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("cantidad")
                        .HasColumnType("numeric");

                    b.Property<int>("tipoMoneda")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("VentaDetalleId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("numeric");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("MonedaDeEntrada")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioMayorista")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecioMinorista")
                        .HasColumnType("numeric");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ImportadoraApi.Models.RegistroFinanciero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlmacenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Moneda")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenciaTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistrosFinancieros");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Venta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cliente")
                        .HasColumnType("text");

                    b.Property<Guid?>("Consignacionid")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TipoVenta")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("ImportadoraApi.Models.VentaDetalle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Impuestos")
                        .HasColumnType("numeric");

                    b.Property<Guid>("InventarioProductoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<Guid>("VentaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventarioProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("VentaDetalles");
                });

            modelBuilder.Entity("ImportadoraApi.Models.CierreDiario", b =>
                {
                    b.HasOne("ImportadoraApi.Models.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("AlmacenId");

                    b.HasOne("ImportadoraApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ImportadoraApi.Models.CierreDiarioRegistro", b =>
                {
                    b.HasOne("ImportadoraApi.Models.CierreDiario", "CierreDiario")
                        .WithMany("Registros")
                        .HasForeignKey("CierreDiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportadoraApi.Models.RegistroFinanciero", "RegistroFinanciero")
                        .WithMany()
                        .HasForeignKey("RegistroFinancieroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CierreDiario");

                    b.Navigation("RegistroFinanciero");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Consignacion", b =>
                {
                    b.HasOne("ImportadoraApi.Models.Venta", "Venta")
                        .WithOne("Consignacion")
                        .HasForeignKey("ImportadoraApi.Models.Consignacion", "VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("ImportadoraApi.Models.ConsignacionMovimiento", b =>
                {
                    b.HasOne("ImportadoraApi.Models.Consignacion", "Consignacion")
                        .WithMany("Movimientos")
                        .HasForeignKey("ConsignacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportadoraApi.Models.Usuario", "Usuario")
                        .WithMany("Consignaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consignacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ImportadoraApi.Models.ContenedorDetalle", b =>
                {
                    b.HasOne("ImportadoraApi.Models.Contenedor", "Contenedor")
                        .WithMany("Detalles")
                        .HasForeignKey("ContenedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportadoraApi.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contenedor");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ImportadoraApi.Models.CostosContenedor", b =>
                {
                    b.HasOne("ImportadoraApi.Models.Contenedor", "contenedorasignado")
                        .WithMany("Costos")
                        .HasForeignKey("Idcotenedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("contenedorasignado");
                });

            modelBuilder.Entity("ImportadoraApi.Models.DistribucionProducto", b =>
                {
                    b.HasOne("ImportadoraApi.Models.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportadoraApi.Models.ContenedorDetalle", null)
                        .WithMany("Distribuciones")
                        .HasForeignKey("ContenedorDetalleId");

                    b.HasOne("ImportadoraApi.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Inventario", b =>
                {
                    b.HasOne("ImportadoraApi.Models.Almacen", "Almacen")
                        .WithOne("inventario")
                        .HasForeignKey("ImportadoraApi.Models.Inventario", "AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Almacen");
                });

            modelBuilder.Entity("ImportadoraApi.Models.InventarioProducto", b =>
                {
                    b.HasOne("ImportadoraApi.Models.Inventario", "Inventario")
                        .WithMany("Productos")
                        .HasForeignKey("InventarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportadoraApi.Models.Producto", "Producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventario");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Merma", b =>
                {
                    b.HasOne("ImportadoraApi.Models.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportadoraApi.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportadoraApi.Models.Usuario", "Usuario")
                        .WithMany("Mermas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ImportadoraApi.Models.MovimientoInventario", b =>
                {
                    b.HasOne("ImportadoraApi.Models.InventarioProducto", "InventarioProducto")
                        .WithMany("Movimientos")
                        .HasForeignKey("InventarioProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportadoraApi.Models.Usuario", "Usuario")
                        .WithMany("Movimientos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventarioProducto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Pagos", b =>
                {
                    b.HasOne("ImportadoraApi.Models.VentaDetalle", null)
                        .WithMany("monedas")
                        .HasForeignKey("VentaDetalleId");
                });

            modelBuilder.Entity("ImportadoraApi.Models.RegistroFinanciero", b =>
                {
                    b.HasOne("ImportadoraApi.Models.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("AlmacenId");

                    b.HasOne("ImportadoraApi.Models.Usuario", "Usuario")
                        .WithMany("RegistrosFinancieros")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Venta", b =>
                {
                    b.HasOne("ImportadoraApi.Models.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportadoraApi.Models.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ImportadoraApi.Models.VentaDetalle", b =>
                {
                    b.HasOne("ImportadoraApi.Models.InventarioProducto", "InventarioProducto")
                        .WithMany()
                        .HasForeignKey("InventarioProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportadoraApi.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventarioProducto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Almacen", b =>
                {
                    b.Navigation("inventario")
                        .IsRequired();
                });

            modelBuilder.Entity("ImportadoraApi.Models.CierreDiario", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Consignacion", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Contenedor", b =>
                {
                    b.Navigation("Costos");

                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ImportadoraApi.Models.ContenedorDetalle", b =>
                {
                    b.Navigation("Distribuciones");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Inventario", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ImportadoraApi.Models.InventarioProducto", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Producto", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Usuario", b =>
                {
                    b.Navigation("Consignaciones");

                    b.Navigation("Mermas");

                    b.Navigation("Movimientos");

                    b.Navigation("RegistrosFinancieros");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("ImportadoraApi.Models.Venta", b =>
                {
                    b.Navigation("Consignacion");

                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ImportadoraApi.Models.VentaDetalle", b =>
                {
                    b.Navigation("monedas");
                });
#pragma warning restore 612, 618
        }
    }
}
